/**
 * Created by gian.jamisola on 5/31/2017.
 */

import {root} from 'nls/common.js';

let localCommon = {
    cntryHeaderTitle: "Terms and Conditions",
    cntryAfghanistan: "Afghanistan",
    cntryAlbania: "Albania",
    cntryAngola: "Angola",
    cntryAustralia: "Australia",
    cntryBelgium: "Belgium",
    cntryBosHerz: "Bosnia and Herzegovina",
    cntryBulgaria: "Bulgaria",
    cntryBurundi: "Burundi",
    cntryCayman: "Cayman Islands",
    cntryChad: "Chad",
    cntryChina: "China",
    cntryCongo: "Congo",
    cntryCyprus: "Cyprus",
    cntryCRepublic: "Czech Republic",
    cntryNoKor: "Democratic People’s Republic of Korea (North)",
    cntryDenmark: "Denmark",
    cntryEstonia: "Estonia",
    cntryEthiopia: "Ethiopia",
    cntryFrance: "France",
    cntryGuernsey: "Guernsey",
    cntryGuinea: "Guinea",
    cntryGuineaBissau: "Guinea-Bissau",
    cntryGuyana: "Guyana",
    cntryHaiti: "Haiti",
    cntryHongKong: "Hong Kong",
    cntryHungary: "Hungary",
    cntryIran: "Iran",
    cntryIraq: "Iraq",
    cntryIreland: "Ireland",
    cntryIsrael: "Israel",
    cntryItaly: "Italy",
    cntryIvoryCoast: "Ivory Coast (Cote d’Ivoire)",
    cntryLao: "Lao",
    cntryLatvia: "Latvia",
    cntryLesotho: "Lesotho",
    cntryLiberia: "Liberia",
    cntryLibya: "Libya",
    cntryMacao: "Macao",
    cntryMali: "Mali",
    cntryMozambique: "Mozambique",
    cntryMyanmar: "Myanmar (Burma)",
    cntryNepal: "Nepal",
    cntryNiger: "Niger",
    cntryNigeria: "Nigeria",
    cntryPalestinianTerritory: "Palestinian Territory",
    cntryPanama: "Panama",
    cntryPapuaNewGuinea: "Papua New Guinea",
    cntryPhilippines: "Philippines",
    cntryPoland: "Poland",
    cntryPortugal: "Portugal",
    cntryRomania: "Romania",
    cntryRussia: "Russia",
    cntrySaoTome: "Sao Tome & Principe",
    cntrySaudiArabia: "Saudi Arabia",
    cntrySerbia: "Serbia",
    cntrySierraLeone: "Sierra Leone",
    cntrySingapore: "Singapore",
    cntrySomalia: "Somalia",
    cntrySpain: "Spain",
    cntrySudan: "Sudan",
    cntrySouthSudan: "South Sudan",
    cntrySwaziland: "Swaziland",
    cntrySwitzerland: "Switzerland",
    cntrySyria: "Syria",
    cntryTaiwan: "Taiwan",
    cntryTajikistan: "Tajikistan",
    cntryTheNetherlands: "The Netherlands",
    cntryTogo: "Togo",
    cntryTurkey: "Turkey",
    cntryUganda: "Uganda",
    cntryUkraine: "Ukraine",
    cntryUSA: "USA and all US territories (American Samoa Guam Northern Mariana Islands Puerto Rico United States Virgin Islands)",
    cntryVanuatu: "Vanuatu",
    cntryVietnam: "Vietnam",
    cntryYemenZambia: "Yemen and Zambia"
}

let combined = Object.assign({}, root, localCommon);

let getValue = (code) => combined[code];

export default getValue;