/**
 * Created by gian.jamisola on 5/23/2017.
 */

import iCommon from 'nls/common';

let countries = [
    {text: iCommon('cntryAfghanistan')},
    {text: iCommon('cntryAlbania')},
    {text: iCommon('cntryAngola')},
    {text: iCommon('cntryAustralia')},
    {text: iCommon('cntryBelgium')},
    {text: iCommon('cntryBosHerz')},
    {text: iCommon('cntryBulgaria')},
    {text: iCommon('cntryBurundi')},
    {text: iCommon('cntryCayman')},
    {text: iCommon('cntryChad')},
    {text: iCommon('cntryChina')},
    {text: iCommon('cntryCongo')},
    {text: iCommon('cntryCyprus')},
    {text: iCommon('cntryCRepublic')},
    {text: iCommon('cntryNoKor')},
    {text: iCommon('cntryDenmark')},
    {text: iCommon('cntryEstonia')},
    {text: iCommon('cntryEthiopia')},
    {text: iCommon('cntryFrance')},
    {text: iCommon('cntryGuernsey')},
    {text: iCommon('cntryGuinea')},
    {text: iCommon('cntryGuineaBissau')},
    {text: iCommon('cntryGuyana')},
    {text: iCommon('cntryHaiti')},
    {text: iCommon('cntryHongKong')},
    {text: iCommon('cntryHungary')},
    {text: iCommon('cntryIran')},
    {text: iCommon('cntryIraq')},
    {text: iCommon('cntryIreland')},
    {text: iCommon('cntryIsrael')},
    {text: iCommon('cntryItaly')},
    {text: iCommon('cntryIvoryCoast')},
    {text: iCommon('cntryLao')},
    {text: iCommon('cntryLatvia')},
    {text: iCommon('cntryLesotho')},
    {text: iCommon('cntryLiberia')},
    {text: iCommon('cntryLibya')},
    {text: iCommon('cntryMacao')},
    {text: iCommon('cntryMali')},
    {text: iCommon('cntryMozambique')},
    {text: iCommon('cntryMyanmar')},
    {text: iCommon('cntryNepal')},
    {text: iCommon('cntryNiger')},
    {text: iCommon('cntryNigeria')},
    {text: iCommon('cntryPalestinianTerritory')},
    {text: iCommon('cntryPanama')},
    {text: iCommon('cntryPapuaNewGuinea')},
    {text: iCommon('cntryPhilippines')},
    {text: iCommon('cntryPoland')},
    {text: iCommon('cntryPortugal')},
    {text: iCommon('cntryRomania')},
    {text: iCommon('cntryRussia')},
    {text: iCommon('cntrySaoTome')},
    {text: iCommon('cntrySaudiArabia')},
    {text: iCommon('cntrySerbia')},
    {text: iCommon('cntrySierraLeone')},
    {text: iCommon('cntrySingapore')},
    {text: iCommon('cntrySomalia')},
    {text: iCommon('cntrySpain')},
    {text: iCommon('cntrySudan')},
    {text: iCommon('cntrySouth Sudan')},
    {text: iCommon('cntrySwaziland')},
    {text: iCommon('cntrySwitzerland')},
    {text: iCommon('cntrySyria')},
    {text: iCommon('cntryTaiwan')},
    {text: iCommon('cntryTajikistan')},
    {text: iCommon('cntryTheNetherlands')},
    {text: iCommon('cntryTogo')},
    {text: iCommon('cntryTurkey')},
    {text: iCommon('cntryUganda')},
    {text: iCommon('cntryUkraine')},
    {text: iCommon('cntryUSA')},
    {text: iCommon('cntryVanuatu')},
    {text: iCommon('cntryVietnam')},
    {text: iCommon('cntryYemenZambia')}
];

export default {countries};